
image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer install
    command: |
      clear
      phpunit --version
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - junstyle.php-cs-fixer
